[0m09:53:43.944939 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x104c15790>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x105ff0ee0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x106039220>]}


============================== 09:53:43.949205 | 7e10d2c2-9fa8-4930-ba8d-6157594bffc6 ==============================
[0m09:53:43.949205 [info ] [MainThread]: Running with dbt=1.5.0
[0m09:53:43.949614 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'version_check': 'True', 'profiles_dir': '/Users/daveconnors/.dbt', 'log_path': 'logs', 'debug': 'False', 'fail_fast': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'True', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'static_parser': 'True', 'log_format': 'default', 'introspect': 'True', 'target_path': 'None', 'send_anonymous_usage_stats': 'True'}
[0m09:53:43.950076 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /Users/daveconnors/dev/dbt-labs/dbt-meshify/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m09:53:43.950575 [debug] [MainThread]: Command `cli parse` failed at 09:53:43.950504 after 0.05 seconds
[0m09:53:43.950812 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x104c15790>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x105ff0100>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x105ff0280>]}
[0m09:53:43.951076 [debug] [MainThread]: Flushing usage events
[0m09:53:44.275084 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x104749160>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x106213a90>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x106213af0>]}


============================== 09:53:44.275504 | 69c2caeb-ab16-48e8-93e8-41c47584a46b ==============================
[0m09:53:44.275504 [info ] [MainThread]: Running with dbt=1.5.0
[0m09:53:44.275792 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'version_check': 'True', 'profiles_dir': '/Users/daveconnors/.dbt', 'log_path': 'logs', 'debug': 'False', 'fail_fast': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'True', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'static_parser': 'True', 'log_format': 'default', 'introspect': 'True', 'target_path': 'None', 'send_anonymous_usage_stats': 'True'}
[0m09:53:44.276121 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /Users/daveconnors/dev/dbt-labs/dbt-meshify/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m09:53:44.276547 [debug] [MainThread]: Command `cli parse` failed at 09:53:44.276480 after 0.00 seconds
[0m09:53:44.276752 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x104749160>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x106213670>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x106213ac0>]}
[0m09:53:44.276967 [debug] [MainThread]: Flushing usage events
[0m09:53:44.452155 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10624a0d0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10624a550>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10624a8e0>]}


============================== 09:53:44.452542 | 2b9adf67-2cc0-43a7-8dad-31241a05d2ff ==============================
[0m09:53:44.452542 [info ] [MainThread]: Running with dbt=1.5.0
[0m09:53:44.452804 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'version_check': 'True', 'profiles_dir': '/Users/daveconnors/.dbt', 'log_path': 'logs', 'debug': 'False', 'fail_fast': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'True', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'static_parser': 'True', 'log_format': 'default', 'introspect': 'True', 'target_path': 'None', 'send_anonymous_usage_stats': 'True'}
[0m09:53:44.453070 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /Users/daveconnors/dev/dbt-labs/dbt-meshify/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m09:53:44.453490 [debug] [MainThread]: Command `cli parse` failed at 09:53:44.453401 after 0.00 seconds
[0m09:53:44.453728 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x104749160>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10624a9d0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10624a730>]}
[0m09:53:44.453962 [debug] [MainThread]: Flushing usage events
[0m09:53:44.634288 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x106039880>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1060399a0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x106039ac0>]}


============================== 09:53:44.634628 | ae60e0a1-d008-495d-baff-2a0583ce7f53 ==============================
[0m09:53:44.634628 [info ] [MainThread]: Running with dbt=1.5.0
[0m09:53:44.634893 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'version_check': 'True', 'profiles_dir': '/Users/daveconnors/.dbt', 'log_path': 'logs', 'debug': 'False', 'fail_fast': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'True', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'static_parser': 'True', 'log_format': 'default', 'introspect': 'True', 'target_path': 'None', 'send_anonymous_usage_stats': 'True'}
[0m09:53:44.635172 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /Users/daveconnors/dev/dbt-labs/dbt-meshify/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m09:53:44.635519 [debug] [MainThread]: Command `cli parse` failed at 09:53:44.635464 after 0.00 seconds
[0m09:53:44.635699 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x106039580>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10624a0d0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10624a550>]}
[0m09:53:44.635903 [debug] [MainThread]: Flushing usage events
[0m09:53:44.807529 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x106039910>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x106039a90>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x106039220>]}


============================== 09:53:44.807886 | b445b60a-5326-4ef2-a205-9e97b29ab04a ==============================
[0m09:53:44.807886 [info ] [MainThread]: Running with dbt=1.5.0
[0m09:53:44.808166 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'version_check': 'True', 'profiles_dir': '/Users/daveconnors/.dbt', 'log_path': 'logs', 'debug': 'False', 'fail_fast': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'True', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'static_parser': 'True', 'log_format': 'default', 'introspect': 'True', 'target_path': 'None', 'send_anonymous_usage_stats': 'True'}
[0m09:53:44.808443 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /Users/daveconnors/dev/dbt-labs/dbt-meshify/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m09:53:44.808801 [debug] [MainThread]: Command `cli parse` failed at 09:53:44.808742 after 0.00 seconds
[0m09:53:44.808989 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1060398e0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x106039be0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10624a640>]}
[0m09:53:44.809189 [debug] [MainThread]: Flushing usage events
[0m09:54:32.763552 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1038e9790>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x104db0eb0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x104df91f0>]}


============================== 09:54:32.767006 | b1ba0be8-1c5a-484e-bf05-4a03cfdc49de ==============================
[0m09:54:32.767006 [info ] [MainThread]: Running with dbt=1.5.0
[0m09:54:32.767368 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'fail_fast': 'False', 'profiles_dir': '/Users/daveconnors/.dbt', 'log_path': 'logs', 'version_check': 'True', 'debug': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'True', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'static_parser': 'True', 'log_format': 'default', 'introspect': 'True', 'target_path': 'None', 'send_anonymous_usage_stats': 'True'}
[0m09:54:32.767735 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /Users/daveconnors/dev/dbt-labs/dbt-meshify/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m09:54:32.768221 [debug] [MainThread]: Command `cli parse` failed at 09:54:32.768145 after 0.03 seconds
[0m09:54:32.768440 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1038e9790>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x104db0250>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x104db0190>]}
[0m09:54:32.768647 [debug] [MainThread]: Flushing usage events
[0m09:54:33.025842 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x104df90a0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x104df9550>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x104df9940>]}


============================== 09:54:33.026241 | 5a59bc38-3f78-4edd-9a46-a8854f8d01e4 ==============================
[0m09:54:33.026241 [info ] [MainThread]: Running with dbt=1.5.0
[0m09:54:33.026527 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'fail_fast': 'False', 'profiles_dir': '/Users/daveconnors/.dbt', 'log_path': 'logs', 'version_check': 'True', 'debug': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'True', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'static_parser': 'True', 'log_format': 'default', 'introspect': 'True', 'target_path': 'None', 'send_anonymous_usage_stats': 'True'}
[0m09:54:33.026818 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /Users/daveconnors/dev/dbt-labs/dbt-meshify/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m09:54:33.027183 [debug] [MainThread]: Command `cli parse` failed at 09:54:33.027124 after 0.00 seconds
[0m09:54:33.027373 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x104df90a0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x104df9850>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x104df97f0>]}
[0m09:54:33.027579 [debug] [MainThread]: Flushing usage events
[0m09:54:33.202253 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x105015970>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x105015670>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1050156d0>]}


============================== 09:54:33.202603 | 818386d5-2782-40d7-858f-491bcb48946c ==============================
[0m09:54:33.202603 [info ] [MainThread]: Running with dbt=1.5.0
[0m09:54:33.202866 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'fail_fast': 'False', 'profiles_dir': '/Users/daveconnors/.dbt', 'log_path': 'logs', 'version_check': 'True', 'debug': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'True', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'static_parser': 'True', 'log_format': 'default', 'introspect': 'True', 'target_path': 'None', 'send_anonymous_usage_stats': 'True'}
[0m09:54:33.203129 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /Users/daveconnors/dev/dbt-labs/dbt-meshify/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m09:54:33.203480 [debug] [MainThread]: Command `cli parse` failed at 09:54:33.203419 after 0.00 seconds
[0m09:54:33.203672 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x105015970>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x105015790>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x105015940>]}
[0m09:54:33.203958 [debug] [MainThread]: Flushing usage events
[0m09:54:33.374141 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10340e400>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x104d92760>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x104d92df0>]}


============================== 09:54:33.374498 | 399f310d-6dd2-47aa-98ee-c77b064ed2d4 ==============================
[0m09:54:33.374498 [info ] [MainThread]: Running with dbt=1.5.0
[0m09:54:33.374756 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'fail_fast': 'False', 'profiles_dir': '/Users/daveconnors/.dbt', 'log_path': 'logs', 'version_check': 'True', 'debug': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'True', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'static_parser': 'True', 'log_format': 'default', 'introspect': 'True', 'target_path': 'None', 'send_anonymous_usage_stats': 'True'}
[0m09:54:33.375030 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /Users/daveconnors/dev/dbt-labs/dbt-meshify/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m09:54:33.375395 [debug] [MainThread]: Command `cli parse` failed at 09:54:33.375338 after 0.00 seconds
[0m09:54:33.375584 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10340e400>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x104d92370>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x104d92430>]}
[0m09:54:33.375833 [debug] [MainThread]: Flushing usage events
[0m09:54:33.547736 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x104d927c0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x104d927f0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x104d92550>]}


============================== 09:54:33.548068 | 591b72b1-0f21-4e20-a77c-5817d6ab0064 ==============================
[0m09:54:33.548068 [info ] [MainThread]: Running with dbt=1.5.0
[0m09:54:33.548313 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'fail_fast': 'False', 'profiles_dir': '/Users/daveconnors/.dbt', 'log_path': 'logs', 'version_check': 'True', 'debug': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'True', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'static_parser': 'True', 'log_format': 'default', 'introspect': 'True', 'target_path': 'None', 'send_anonymous_usage_stats': 'True'}
[0m09:54:33.548560 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /Users/daveconnors/dev/dbt-labs/dbt-meshify/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m09:54:33.548877 [debug] [MainThread]: Command `cli parse` failed at 09:54:33.548828 after 0.00 seconds
[0m09:54:33.549050 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x104d927c0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x105001520>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x105001490>]}
[0m09:54:33.549245 [debug] [MainThread]: Flushing usage events
